/**
 *存放action类型
 */


/*登录模块*/
export const WECHAT_LOGIN_DOING = 'WECHAT_LOGIN_DOING';
export const WECHAT_LOGIN_SUCCESS = 'WECHAT_LOGIN_SUCCESS';
export const WECHAT_LOGIN_ERROR = 'WECHAT_LOGIN_ERROR';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';

/*资源模块*/

//请求资源列表
export const FETCH_RESOURCE_LIST_DOING = 'FETCH_RESOURCE_LIST_DOING';
export const FETCH_RESOURCE_LIST_SUCCESS = 'FETCH_RESOURCE_LIST_SUCCESS';
export const FETCH_RESOURCE_LIST_ERROR = 'FETCH_RESOURCE_LIST_ERROR';

//发布资源
export const RELEASE_RESOURCE_DOING = 'RELEASE_RESOURCE_DOING';
export const RELEASE_RESOURCE_SUCCESS = 'RELEASE_RESOURCE_SUCCESS';
export const RELEASE_RESOURCE_ERROR = 'RELEASE_RESOURCE_ERROR';
