/**
 *存放action类型
 */

/*登录模块*********************************************************/
export const WECHAT_LOGIN_DOING = 'WECHAT_LOGIN_DOING';
export const WECHAT_LOGIN_SUCCESS = 'WECHAT_LOGIN_SUCCESS';
export const WECHAT_LOGIN_ERROR = 'WECHAT_LOGIN_ERROR';

export const HAS_TOKEN = 'HAS_TOKEN';
export const NO_TOKEN = 'NO_TOKEN';

export const DELETE_TOKEN = 'DELETE_TOKEN';


/*资源模块**********************************************************/
export const FETCH_RESOURCE_LIST_DOING = 'FETCH_RESOURCE_LIST_DOING';
export const FETCH_RESOURCE_LIST_SUCCESS = 'FETCH_RESOURCE_LIST_SUCCESS';
export const FETCH_RESOURCE_LIST_ERROR = 'FETCH_RESOURCE_LIST_ERROR';

export const RELEASE_RESOURCE_DOING = 'RELEASE_RESOURCE_DOING';
export const RELEASE_RESOURCE_SUCCESS = 'RELEASE_RESOURCE_SUCCESS';

export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';

export const ADD_RESOURCE_DESC_DOING = 'ADD_RESOURCE_DESC_DOING';
export const ADD_RESOURCE_DESC_SUCCESS = 'ADD_RESOURCE_DESC_SUCCESS';
export const ADD_RESOURCE_DESC_ERROR = 'ADD_RESOURCE_DESC_ERROR';

export const FETCH_RESOURCE_CUSTMER_INFO = 'FETCH_RESOURCE_CUSTMER_INFO';

export const FETCH_RESOURCE_FEATURE_INFO = 'FETCH_RESOURCE_FEATURE_INFO';

/*订单模块**********************************************************/

export const FETCH_ORDER_LIST_DOING = 'FETCH_ORDER_LIST_DOING';
export const FETCH_ORDER_LIST_SUCCESS = 'FETCH_ORDER_LIST_SUCCESS';
export const FETCH_ORDER_LIST_ERROR = 'FETCH_ORDER_LIST_ERROR';

export const FETCH_ORDER_DETAIL_SUCCESS = 'FETCH_ORDER_DETAIL_SUCCESS';


/*消息模块**********************************************************/

export const FETCH_MESSAGE_LIST_DOING = 'FETCH_MESSAGE_LIST_DOING';
export const FETCH_MESSAGE_LIST_SUCCESS = 'FETCH_MESSAGE_LIST_SUCCESS';
export const FETCH_MESSAGE_LIST_ERROR = 'FETCH_MESSAGE_LIST_ERROR';

export const FETCH_CLIENT_LIST_SUCCESS = 'FETCH_CLIENT_LIST_SUCCESS';

export const FETCH_SINGLE_MESSAGE_DOING = 'FETCH_SINGLE_MESSAGE_DOING';
export const FETCH_SINGLE_MESSAGE_SUCCESS = 'FETCH_SINGLE_MESSAGE_SUCCESS';
export const FETCH_SINGLE_MESSAGE_ERROR = 'FETCH_SINGLE_MESSAGE_ERROR';


/*关于模块**********************************************************/

export const FETCH_ABOUTINFO_DOING = 'FETCH_ABOUTINFO_DOING';
export const FETCH_ABOUTINFO_SUCCESS = 'FETCH_ABOUTINFO_SUCCESS';
export const FETCH_ABOUTINFO_ERROR = 'FETCH_ABOUTINFO_ERROR';

export const UPLOAD_PAYMENTMETHODS_DOING = 'UPLOAD_PAYMENTMETHODS_DOING';
export const UPLOAD_PAYMENTMETHODS_SUCCESS = 'UPLOAD_PAYMENTMETHODS_SUCCESS';
export const UPLOAD_PAYMENTMETHODS_ERROR = 'UPLOAD_PAYMENTMETHODS_ERROR';

/*TAB管理模块**********************************************************/

export const HIDDEN_TAB_BAR = 'HIDDEN_TAB_BAR';
export const SHOW_TAB_BAR = 'SHOW_TAB_BAR';


